title: cci.dev
description: Lead the CC Incarnadine and her crew of climate-punks, nautical drones, and GMO algae on a mission to heal the desiccated coral reefs.
twitter_site: "@tyleretters"
twitter_creator: "@tyleretters"
twitter_image_src: /assets/images/coral_carrier_incarnadine.gif
og_image: /assets/images/coral_carrier_incarnadine.gif
baseurl: /
url: https://cci.dev
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap